# -*- coding: utf-8 -*-
"""wine_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JbTKPKm_AFsrTEbYRhiUvi52dIYgdzlg

# 특성 이름 확인
"""

from sklearn.datasets import load_wine

wine = load_wine()

"""## 데이터셋 구조 확인"""

print("데이터 크기:", wine.data.shape)
print("정답 크기:", wine.target.shape)

print("\n와인 종류:")
print(wine.target_names)

print("\n특성 개수:")
print(len(wine.feature_names))

"""## 특성 이름 확인"""

print(wine.feature_names)

"""## 학습 데이터와 테스트 데이터 분리"""

from sklearn.model_selection import train_test_split

X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("학습 데이터:", X_train.shape)
print("테스트 데이터:", X_test.shape)

"""## KNN 모델 학습"""

from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier()

kn.fit(X_train, y_train)

"""## KNN 모델 정확도 평가"""

print("학습 정확도 :", kn.score(X_train, y_train))
print("테스트 정확도 :", kn.score(X_test, y_test))

"""## Decision Tree 모델 학습"""

from sklearn.tree import DecisionTreeClassifier

tree_model = DecisionTreeClassifier(random_state=42)

tree_model.fit(X_train, y_train)

"""## Decision Tree 모델 정확도 평가"""

print("학습 정확도 :", tree_model.score(X_train, y_train))
print("테스트 정확도 :", tree_model.score(X_test, y_test))

"""## Logistic Regression 모델 학습"""

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=3000)

lr_model.fit(X_train, y_train)

"""## Logistic Regression 모델 정확도 평가"""

print("학습 정확도 :", lr_model.score(X_train, y_train))
print("테스트 정확도 :", lr_model.score(X_test, y_test))